# 인덱싱과 슬라이싱을 이용한 배열의 원소 조회

## 배열 인덱싱(Indexing)
- index
    - 배열내의 원소의 식별번호
    - 0부터 시작
- indexing 
    – index를 이용해 원소 조회
    - [] 표기법 사용
- 구문 
    - ndarray[index]
    - 양수는 지정한 index의 값을 조회한다. 
    - 음수는 뒤부터 조회한다. 
        - 마지막 index가 -1
    - 2차원배열의 경우 
        - arr[행index, 열index]
        - 파이썬 리스트와 차이점 (list[행][열])
- 팬시(fancy) 인덱싱
    - 여러개의 원소를 조회할 경우 리스트에 담아 전달한다.

In [3]:
l=[
    [2,3,4],
    [10,20,30]
]
# 2
l[0][1]

3

In [4]:
import numpy as np
arr=np.array(l)
arr.shape

(2, 3)

In [5]:
arr[0][1]

3

In [6]:
arr[0,1]

3

In [8]:
arr2=np.arange(2*3*4).reshape(2,3,4)
arr2.shape

(2, 3, 4)

In [13]:
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
arr2[0][2][2]

10

In [15]:
arr2[0,2,2]

10

In [9]:
arr2[0,2,2]=10000
arr2

array([[[    0,     1,     2,     3],
        [    4,     5,     6,     7],
        [    8,     9, 10000,    11]],

       [[   12,    13,    14,    15],
        [   16,    17,    18,    19],
        [   20,    21,    22,    23]]])

In [10]:
arr3=np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr3[0]

0

In [14]:
arr3[[0,3,4]]  # 여러 index의 값들을 한번에 조회할 경우 list로 묶어서 조회 => Fancy Indexing

array([0, 3, 4])

In [15]:
arr2

array([[[    0,     1,     2,     3],
        [    4,     5,     6,     7],
        [    8,     9, 10000,    11]],

       [[   12,    13,    14,    15],
        [   16,    17,    18,    19],
        [   20,    21,    22,    23]]])

In [17]:
arr2[0,0,1]

1

In [18]:
arr4=np.arange(6).reshape(2,3)
arr4

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
arr4[0,0], arr4[1,2]

(0, 5)

In [22]:
arr4[[0,1],[0,2] ]

array([0, 5])

In [26]:
arr2[0,2,2],arr2[0,2,3]

(10000, 11)

In [28]:
arr2[[0,0],[2,2],[2,3]]

array([10000,    11])

In [29]:
arr2[0]

array([[    0,     1,     2,     3],
       [    4,     5,     6,     7],
       [    8,     9, 10000,    11]])

In [30]:
arr2[0,1]

array([4, 5, 6, 7])

In [34]:
arr2[[0,0],[1,2]]

array([[    4,     5,     6,     7],
       [    8,     9, 10000,    11]])

## 슬라이싱
- 배열의 부분 집합을 하위배열로 조회 및 변경하는 방식
- ndarry[start : stop : step ]
    - start : 시작 인덱스. 기본값 0
    - stop : 끝 index. stop은 포함하지 않는다. 기본값 마지막 index
    - step : 증감 간격. 기본값 1)

In [37]:
import numpy as np
arr1=np.arange(100)
arr1.shape

(100,)

In [39]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
arr1[5:10]

array([5, 6, 7, 8, 9])

In [41]:
arr1[80:-5]

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94])

In [42]:
arr1[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [43]:
arr2=arr1.reshape(4,25)
arr2.shape

(4, 25)

In [47]:
arr2[0:3,]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74]])

In [48]:
arr2[0:3, 6:9]

array([[ 6,  7,  8],
       [31, 32, 33],
       [56, 57, 58]])

In [49]:
arr2[1:3,7:12]

array([[32, 33, 34, 35, 36],
       [57, 58, 59, 60, 61]])

In [51]:
arr2[1:3,7]

array([32, 57])

In [52]:
arr2[1:3, [7,9]]

array([[32, 34],
       [57, 59]])

In [53]:
arr2[[1,2], 5:10]

array([[30, 31, 32, 33, 34],
       [55, 56, 57, 58, 59]])

In [ ]:
# ND 텐서 (n차원 배열)
# arr[0,1,2,3,4,5,...,n]

### 다차원 배열 슬라이싱
- 각 축에 slicing 문법 적용
- 2차원의 경우
    - arr [행 slicing, 열 slicing]
    - `,` 로 행과 열을 구분한 다중 슬라이싱 사용

### 슬라이싱은 원본에 대한 View 
- slicing한 결과는 새로운 배열을 생성하는 것이 아니라 기존 배열을 참조한다.
- slicing한 배열의 원소를 변경하면 원본 배열의 것도 바뀐다.
- 배열.copy()
    - 배열을 복사한 새로운 배열 생성
    - 복사후 처리하면 원본이 바뀌지 않는다.

In [54]:
import numpy as np
arr=np.zeros(shape=(3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
arr2=arr[:2, :2]
arr2.shape

(2, 2)

In [60]:
arr2

array([[0., 0.],
       [0., 0.]])

In [62]:
arr2[0,0]=1 # 변경
arr2

array([[1., 0.],
       [0., 0.]])

In [63]:
arr # 원본도 함께 변경됨 -> 원본은 변경하지 않으려면 copy처리 후 변경

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
arr3=arr[:2,:2].copy() # 복사본 반환 => deep copy

In [66]:
print(arr3.shape)
arr3

(2, 2)


array([[1., 0.],
       [0., 0.]])

In [69]:
arr3[0,0]=100
print(arr3) # 변경
arr  # 원본은 변경되지 않음

[[100.   0.]
 [  0.   0.]]


array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### boolean indexing
- Index 연산자에 Boolean 배열을 넣으면 True인 index의 값만 조회
- ndarray내의 원소 중에서 원하는 조건의 값들만 조회할 때 사용

In [72]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
i=np.random.choice([True,False], size=10)
i

array([False,  True, False, False,  True,  True,  True,  True,  True,
       False])

In [76]:
a[i] # i의 True인 index값 반환

array([1, 4, 5, 6, 7, 8])

넘파이 -> 벡터화(Vectorization) 연산
배열 연산 값 = 배열의 각 원소별로 연산을 처리

In [82]:
a+10, a*10

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [85]:
i=a>5
a[i]

array([6, 7, 8, 9])

In [84]:
a[a>5]

array([6, 7, 8, 9])

In [86]:
# a에서 3의 배수만 조회
a[a%3==0]

array([0, 3, 6, 9])

In [91]:
# 3~6: 넘파이: and, or => &,|
a[(a>=3) & (a<=6)]

array([3, 4, 5, 6])

In [93]:
a[(a<2)|(a>6)]

array([0, 1, 7, 8, 9])

In [94]:
# 특정 조건을 만족하는 값들의 index 조회
np.where(a>5)

(array([6, 7, 8, 9], dtype=int64),)

In [96]:
a2=a*10
np.where(a2<30)

(array([0, 1, 2], dtype=int64),)

In [97]:
a2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [98]:
np.where(a2<30, "30미만","30이상") # (조건, True인 index에 넣을 값, False인 index에 넣을 값)

array(['30미만', '30미만', '30미만', '30이상', '30이상', '30이상', '30이상', '30이상',
       '30이상', '30이상'], dtype='<U4')

In [99]:
np.all([True,True,True])  # 모든 원소가 True이면 True

True

In [100]:
np.all([True,False,True])

False

In [102]:
np.any([True,False,False]) # 원소 중 한개라도 True이면 True

True

In [103]:
np.any([False,False,False])

False

In [106]:
np.any(a>3)  # 배열 내 원소 중 3보다 큰 값이 한개라도 존재하니?

True

In [111]:
np.all(a>3)  # 배열 내 모든 원소가 3보다 크니?

False