# 배열의 재구조화
- 배열의 차수 변경
- `numpy.reshape(a, newshape)` 또는 `ndarray.reshape(newshape)`
    - a: 형태를 변경할 배열
    - newshape : 변경할 형태 설정. 
        - 원소의 개수를 유지하는 shape으로 만 변환 가능하다.


In [1]:
import numpy as np

In [2]:
x=np.arange(10,20)
x.shape

(10,)

In [3]:
np.reshape(x, (2,5))

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
x.reshape((2,5))

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
x.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
# 원래 배열과 reshape되는 배열의 size(원소의 개수)는 동일해야 한다.
x.reshape(2,4)

ValueError: cannot reshape array of size 10 into shape (2,4)

## slicing에서 np.newaxis 이용해 차원 늘리기
- 차원을 늘릴때 사용한다. 
- 지정한 곳에 size 1인 축을 추가한다.

### slicing에서 사용한다. 

In [17]:
print(x.shape)
x

(10,)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
x[:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
x1=x[np.newaxis, :]
print(x1.shape)
x1

(1, 10)


array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [24]:
x2=x[:, np.newaxis]
x2

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [27]:
y=np.arange(128*128).reshape(128,128)
y.shape

(128, 128)

In [32]:
y1=y[:,:,np.newaxis]
print(y1.shape)
y1

(128, 128, 1)


array([[[    0],
        [    1],
        [    2],
        ...,
        [  125],
        [  126],
        [  127]],

       [[  128],
        [  129],
        [  130],
        ...,
        [  253],
        [  254],
        [  255]],

       [[  256],
        [  257],
        [  258],
        ...,
        [  381],
        [  382],
        [  383]],

       ...,

       [[16000],
        [16001],
        [16002],
        ...,
        [16125],
        [16126],
        [16127]],

       [[16128],
        [16129],
        [16130],
        ...,
        [16253],
        [16254],
        [16255]],

       [[16256],
        [16257],
        [16258],
        ...,
        [16381],
        [16382],
        [16383]]])

In [34]:
z=np.arange(12).reshape(4,3)
print(z.shape)
z

(4, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
z1=z[:, np.newaxis, :]
z1.shape

(4, 1, 3)

In [36]:
z1

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [41]:
z2=z[:,:,np.newaxis]
z2.shape

(4, 3, 1)

In [44]:
z3=z2[:,:,0]
z3.shape

(4, 3)

### ... 표기와 사용
- 첫번째 또는 마지막에 축을 추가할 때 사용가능

In [45]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
x[..., np.newaxis].shape

(10, 1)

In [47]:
z.shape

(4, 3)

In [48]:
z[...,np.newaxis].shape

(4, 3, 1)

In [51]:
z[np.newaxis,...].shape

(1, 4, 3)

## 배열 합치기
- p.concatenate(합칠 배열리스트, axis=0)
    - 여러 배열을 **축의개수(rank)**를 유지하며 합친다.
    - axis 파라미터 : 축지정
        - 지정된 축을 기준으로 합친다. 
        - default : 0
    - 합치는 배열의 축의개수(rank) 은 같아야 한다.
    - axis속성으로 지정한 축을 이외의 축의 크기가 같아야 한다.
    - 결과의 축의개수(rank)는 대상 배열의 rank와 같다.
        - 1차원끼리 합치면 1차원결과가 나옴
- 합칠 대상 배열의 rank가 2일 경우(2차원) 
    - vstack()
    - hstack()
- vstack(합칠배열리스트)
    - 수직으로 쌓는다.
    - concatenate() 의 axis=0 와 동일
    - 합칠 배열들의 열수가 같아야 한다.
- hstack(합칠배열리스트)
    - 수평으로 쌓는다.
    - concatenate() 의 axis=1 와 동일
    - 합칠 배열들의 행 수가 같아야 한다.

### concatenate()

In [55]:
import numpy as np
x=np.arange(10)
y=np.arange(5)
z=np.concatenate([x,y])  # axis=0 (기본값 0)
print(z.shape)
z

(15,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4])

In [57]:
w=np.arange(100,200,10)
z2=np.concatenate([x,y,w])
print(z2.shape)
z2

(25,)


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,   0,   1,   2,
         3,   4, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [60]:
a=np.arange(10).reshape(2,5)
b=np.arange(20,30).reshape(2,5)
a.shape, b.shape

((2, 5), (2, 5))

In [62]:
c1=np.concatenate([a,b])
c1.shape

(4, 5)

In [63]:
c1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [64]:
c2=np.concatenate([a,b],axis=1)
c2.shape

(2, 10)

In [65]:
c2

array([[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29]])

In [66]:
i=np.arange(12).reshape(2,3,2)
j=np.arange(10,22).reshape(2,3,2)
i.shape, j.shape

((2, 3, 2), (2, 3, 2))

In [67]:
k=np.concatenate([i,j])
print(k.shape)

(4, 3, 2)


In [68]:
    k

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21]]])

In [70]:
k2=np.concatenate([i,j],axis=1)
k2.shape

(2, 6, 2)

In [71]:
k2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11],
        [16, 17],
        [18, 19],
        [20, 21]]])

In [73]:
k3=np.concatenate([i,j],axis=2)
print(k3.shape)
k3

(2, 3, 4)


array([[[ 0,  1, 10, 11],
        [ 2,  3, 12, 13],
        [ 4,  5, 14, 15]],

       [[ 6,  7, 16, 17],
        [ 8,  9, 18, 19],
        [10, 11, 20, 21]]])

### vstack()
- 아래에 붙이는 개념이므로 열수가 맞아야 한다. (수직 아래 방향으로 추가)

In [75]:
np.vstack([a,b])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [76]:
# np.vstack([i,j])

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21]]])

### hstack()
- 옆으로 붙이는 것이므로 행 수가 같아야 한다. (수평 우방향으로 추가)

In [77]:
np.hstack([a,b])

array([[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29]])

In [80]:
aa=np.arange(6).reshape(2,3)
bb=np.arange(10).reshape(2,5)
np.concatenate([aa,bb],axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

## 배열 분할 하기
- split(배열, 분할기준, axis)
    - 지정한 축을 기준으로 배열을 나눈다.. - 리턴: 분할한 narray를 가진 리스트로 리턴.
    - 배열: 분할할 배열
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
    - axis(축)
        - 분할할 기준 축을 지정한다. axis = 0 (기본) 
        - 2D의 경우 axis=0: 행 기준 분할, axis=1: 열 기준 분할
- vsplit(배열, 분할기준)
    - 행 기준 분할
    - split()의 axis=0과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- hsplit(배열, 분할기준)
    - 열 기준 분할
    - split()의 axis=1과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들


In [81]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4])

In [84]:
a1,a2,a3=np.split(z,3)
a1.shape,a2.shape,a3.shape

((5,), (5,), (5,))

In [85]:
np.split(z,[3])

[array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4])]

In [86]:
np.split(z,[3,5,11])  # 배열의 3,5,11번을 기준으로 분리

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8, 9, 0]),
 array([1, 2, 3, 4])]

In [87]:
np.split(z,2)

ValueError: array split does not result in an equal division

### hsplit()

In [88]:
z=np.arange(20).reshape(4,5)
z.shape

(4, 5)

In [91]:
r=np.hsplit(z,[2])  # axis=1
print(r[0].shape, r[1].shape)

(4, 2) (4, 3)


In [92]:
r2=np.vsplit(z,2) # axis=0
print(r2[0].shape, r2[1].shape)

(2, 5) (2, 5)


### vsplit()